### ISSUE TITLE
Assess site security

### ISSUE THREAD

**Issue by hayleyw7** [nditcommunity/nditcommunity.github.io#28]

**Comment by royemosby** [comment]
GH pages and Netlify deploys are https by default and have their own automated cert update process

**Comment by marcusolsson** [comment]
Right now we're using `mailto:` links with the contact email, which means that email harvesters may pick it up to send spam. There have also been a few vulnerabilities related to mailto links. 

If it's important that visitors can contact the team using email, we could also consider a contact form. [Netlify Forms](https://www.netlify.com/platform/core/forms/) looks like a good solution since we don't have a backend (though I've never used it myself).

**Comment by marcusolsson** [comment]
I don't disagree 🙂 Just thought I'd at least mention it. AFAIK the attack vector is more client side.
