### ISSUE TITLE
Improve design

### ISSUE THREAD

**Issue by hayleyw7** [nditcommunity/nditcommunity.github.io#68]
The design is very simple and bland. Can we spruce it up and make it look more modern?

https://github.com/nditcommunity/nditcommunity.github.io/pull/87

**Comment by galactic-src** [comment]
This is totally the kind of thing we could do in small iterations rather than one big PR :sparkles: 

Some changes might just require styling, more ambitious ones might take some structural change. And I guess we should be aware we're potentially setting up patterns for others to follow, so might want a bit of thought before committing.

It would be super-helpful to pull together some kind of mood board of little screen grabs of the kind of styles you have in mind. Or even just link out to some sites that have the kind of look/feel you'd like for NDIT!
